spring.datasource.url=jdbc:postgresql://localhost:5432/aad
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.web-application-type=none
logging.level.root=INFO
spring.application.name=aad
